/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ic70_kkplayer_kkplayer_CJniKKPlayer */
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>
#ifndef _Included_com_ic70_kkplayer_kkplayer_CJniKKPlayer
#define _Included_com_ic70_kkplayer_kkplayer_CJniKKPlayer




#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ic70_kkplayer_kkplayer_CJniKKPlayer
 * Method:    IniKK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_IniKK
  (JNIEnv *pEv, jobject);

JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_IniGl(JNIEnv *env, jobject instance, jint obj);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_Resizeint(JNIEnv *env, jobject instance, jint obj, jint w, jint h);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_GlRender(JNIEnv *env, jobject instance, jint obj);
JNIEXPORT void JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_DelKK(JNIEnv *env, jobject instance);
#ifdef __cplusplus
}
#endif
#endif
