/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ic70_kkplayer_kkplayer_CJniKKPlayer */
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>
#ifndef _Included_com_ic70_kkplayer_kkplayer_CJniKKPlayer
#define _Included_com_ic70_kkplayer_kkplayer_CJniKKPlayer


JNIEXPORT jint JNICALL
Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_GetCapImg(JNIEnv *env, jobject instance, jobject obj)
{
     jclass cls_objClass=env->GetObjectClass( obj);
     jfieldID ImgPixfmtId=env->GetFieldID(cls_objClass,"ImgPixfmt","Ljava/lang/String;");
     jstring BGR= env->NewStringUTF("BGR");
     env->SetObjectField(obj,ImgPixfmtId,BGR);


     jfieldID imgHeightId=env->GetFieldID(cls_objClass,"imgHeight","I");
     env->SetIntField(obj,imgHeightId,1);
     jfieldID imgWidthId=env->GetFieldID(cls_objClass,"imgWidth","I");
     env->SetIntField(obj,imgWidthId,2);

     jfieldID dataSizeId=env->GetFieldID(cls_objClass,"dataSize","I");
     env->SetIntField(obj, dataSizeId,100);

     jfieldID ImgDataId=env->GetFieldID(cls_objClass,"ImgData","[");
     jbyteArray dataImg= env->NewByteArray(100);
     env->SetObjectField(obj, ImgDataId,dataImg);

     //jfieldID ImgPixfmtId=env->GetFieldID(cls_objClass,"ImgPixfmt","Ljava/lang/String;");
}

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ic70_kkplayer_kkplayer_CJniKKPlayer
 * Method:    IniKK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_IniKK
  (JNIEnv *pEv, jobject);

JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_IniGl(JNIEnv *env, jobject instance, jint obj);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_Resizeint(JNIEnv *env, jobject instance, jint obj, jint w, jint h);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_GlRender(JNIEnv *env, jobject instance, jint obj);
JNIEXPORT void JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_DelKK(JNIEnv *env, jobject instance,jint obj);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKOpenMedia(JNIEnv *env, jobject instance, jstring str_,jint obj);
JNIEXPORT jstring JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_GetMediaInfo(JNIEnv *env, jobject instance, jint obj);
JNIEXPORT void JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_Pause(JNIEnv *env, jobject instance,jint obj);
JNIEXPORT void JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_Seek(JNIEnv *env, jobject instance, jint obj, jint value);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKIsNeedReConnect(JNIEnv *env, jobject instance,jint obj);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKCloseMedia(JNIEnv *env, jobject instance,jint obj);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKGetPlayerState(JNIEnv *env, jobject instance,jint obj);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKIsReady(JNIEnv *env, jobject instance,jint obj);
JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKGetRealtime(JNIEnv *env, jobject instance,jint obj);

JNIEXPORT jint JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKGetRealtimeDelay(JNIEnv *env, jobject instance,jint obj);
JNIEXPORT void JNICALL Java_com_ic70_kkplayer_kkplayer_CJniKKPlayer_KKForceFlushQue(JNIEnv *env, jobject instance,jint obj);
#ifdef __cplusplus
}
#endif
#endif
